### ISSUE TITLE
catkin fails to build complex sources

### ISSUE THREAD

**Issue by sergiusens** [ubuntu-core/snapcraft#68]
A `snapcraft.yaml` that looks like

```yaml
    name: jsk
    version: 0
    vendor: Vendor <email@example.com>
    summary: jsk_robot testing
    description: test builds
    icon: icon.png

    parts:
      ros:
        plugin: roscore
      jsk-robot:
        plugin: catkin
        source: https://github.com/jsk-ros-pkg/jsk_robot.git
        source-type: git
        catkin-packages:
          - jsk_robot_startup
        after:
          - ros
```

Because `jsk_robot_startup` lives in a subdirectory in `jsk_robot_common`
